/**
 * ⏰ Time-Travel Slider Component
 *
 * A sophisticated timeline control that allows operators to navigate through
 * historical flood data and future predictions generated by MindSpore models.
 *
 * Key Features:
 * - Bidirectional timeline (-3h to +3h)
 * - Real-time "NOW" marker
 * - Color-coded past/future tracks
 * - Playback animation with speed control
 * - Bookmark critical moments
 * - Integration with Zustand store for state sync
 */

'use client';

import React, { useState, useEffect, useRef, useCallback } from 'react';
import { Play, Pause, Bookmark, Info } from 'lucide-react';
import { useMapStore } from '@/lib/stores/map-store';

interface TimeTravelSliderProps {
  /** Range in minutes from NOW */
  range?: { min: number; max: number };
  /** Step interval in minutes */
  step?: number;
  /** Callback when time changes */
  onTimeChange?: (offset: number, timestamp: Date) => void;
  /** Critical moments to highlight */
  bookmarks?: Array<{
    offset: number;
    label: string;
    severity: 'info' | 'warning' | 'danger';
  }>;
  /** Loading state for async data fetching */
  isLoading?: boolean;
}

export const TimeTravelSlider: React.FC<TimeTravelSliderProps> = ({
  range = { min: -180, max: 180 }, // -3h to +3h
  step = 30, // 30-minute intervals
  onTimeChange,
  bookmarks = [],
  isLoading = false,
}) => {
  // Zustand store integration
  const {
    timeOffset,
    isPlaying,
    playbackSpeed,
    setTimeOffset,
    togglePlayback,
    setPlaybackSpeed,
  } = useMapStore();

  // Local state for tooltip
  const [showTooltip, setShowTooltip] = useState(false);
  const [tooltipPosition, setTooltipPosition] = useState(0);

  // Refs
  const sliderRef = useRef<HTMLDivElement>(null);
  const animationFrameRef = useRef<number>();

  // Calculate current timestamp
  const getCurrentTimestamp = useCallback((offset: number): Date => {
    const now = new Date();
    return new Date(now.getTime() + offset * 60 * 1000);
  }, []);

  // Playback animation
  useEffect(() => {
    if (!isPlaying) {
      if (animationFrameRef.current) {
        cancelAnimationFrame(animationFrameRef.current);
      }
      return;
    }

    let lastTime = Date.now();
    const animate = () => {
      const currentTime = Date.now();
      const deltaTime = currentTime - lastTime;

      // Calculate step based on playback speed
      const timeStep = (deltaTime / 1000) * playbackSpeed * 30; // 30 minutes per second at 1x

      setTimeOffset(Math.min(timeOffset + timeStep, range.max));

      // Loop back to start when reaching end
      if (timeOffset >= range.max) {
        setTimeOffset(range.min);
      }

      lastTime = currentTime;
      animationFrameRef.current = requestAnimationFrame(animate);
    };

    animationFrameRef.current = requestAnimationFrame(animate);

    return () => {
      if (animationFrameRef.current) {
        cancelAnimationFrame(animationFrameRef.current);
      }
    };
  }, [isPlaying, timeOffset, playbackSpeed, range, setTimeOffset]);

  // Handle slider change
  const handleSliderChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = parseFloat(e.target.value);
    setTimeOffset(value);
    if (onTimeChange) {
      onTimeChange(value, getCurrentTimestamp(value));
    }
  };

  // Calculate percentage for styling
  const percentage = ((timeOffset - range.min) / (range.max - range.min)) * 100;
  const nowPercentage = ((0 - range.min) / (range.max - range.min)) * 100;

  // Format time display
  const formatTimeOffset = (offset: number): string => {
    const absOffset = Math.abs(offset);
    const hours = Math.floor(absOffset / 60);
    const minutes = absOffset % 60;

    const sign = offset < 0 ? '-' : '+';
    const timeStr = hours > 0
      ? `${hours}h ${minutes}m`
      : `${minutes}m`;

    return offset === 0 ? 'NOW' : `${sign}${timeStr}`;
  };

  // Format timestamp display
  const formatTimestamp = (offset: number): string => {
    const timestamp = getCurrentTimestamp(offset);
    return new Intl.DateTimeFormat('th-TH', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    }).format(timestamp);
  };

  // Get bookmark color
  const getBookmarkColor = (severity: string) => {
    switch (severity) {
      case 'danger': return 'bg-red-500';
      case 'warning': return 'bg-yellow-500';
      default: return 'bg-blue-500';
    }
  };

  return (
    <div className="w-full space-y-4 p-6 bg-white/95 backdrop-blur-lg rounded-2xl shadow-xl border border-gray-200">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="flex items-center justify-center w-10 h-10 rounded-full bg-gradient-to-r from-blue-500 to-purple-500">
            <svg
              className="w-5 h-5 text-white"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-gray-900">
              Flood Forecast Timeline
            </h3>
            <p className="text-sm text-gray-500">
              Navigate through time to see predictions
            </p>
          </div>
        </div>

        {/* Playback Controls */}
        <div className="flex items-center gap-2">
          {/* Speed Control */}
          <div className="flex items-center gap-1 px-3 py-1.5 bg-gray-100 rounded-lg">
            {[1, 2, 4].map((speed) => (
              <button
                key={speed}
                onClick={() => setPlaybackSpeed(speed as 1 | 2 | 4)}
                className={`px-2 py-1 text-xs font-medium rounded transition-colors ${
                  playbackSpeed === speed
                    ? 'bg-blue-500 text-white'
                    : 'text-gray-600 hover:bg-gray-200'
                }`}
              >
                {speed}x
              </button>
            ))}
          </div>

          {/* Play/Pause Button */}
          <button
            onClick={togglePlayback}
            disabled={isLoading}
            className="flex items-center justify-center w-10 h-10 rounded-lg bg-blue-500 hover:bg-blue-600 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors text-white"
            aria-label={isPlaying ? 'Pause' : 'Play'}
          >
            {isPlaying ? <Pause className="w-5 h-5" /> : <Play className="w-5 h-5" />}
          </button>
        </div>
      </div>

      {/* Current Time Display */}
      <div className="flex items-center justify-between px-4 py-3 bg-gradient-to-r from-blue-50 to-purple-50 rounded-xl border border-blue-200">
        <div className="flex items-center gap-3">
          <div className="flex flex-col">
            <span className="text-xs font-medium text-gray-600">
              Current View
            </span>
            <span className="text-2xl font-bold text-gray-900">
              {formatTimeOffset(timeOffset)}
            </span>
          </div>
          <div className="h-8 w-px bg-gray-300" />
          <div className="flex flex-col">
            <span className="text-xs font-medium text-gray-600">
              Absolute Time
            </span>
            <span className="text-lg font-semibold text-gray-800">
              {formatTimestamp(timeOffset)}
            </span>
          </div>
        </div>

        {/* Loading Indicator */}
        {isLoading && (
          <div className="flex items-center gap-2 text-blue-600">
            <div className="w-4 h-4 border-2 border-blue-600 border-t-transparent rounded-full animate-spin" />
            <span className="text-sm font-medium">Loading forecast...</span>
          </div>
        )}
      </div>

      {/* Slider Container */}
      <div className="relative pt-8 pb-4" ref={sliderRef}>
        {/* Bookmarks */}
        {bookmarks.map((bookmark, index) => {
          const bookmarkPercentage = ((bookmark.offset - range.min) / (range.max - range.min)) * 100;
          return (
            <div
              key={index}
              className="absolute top-0 transform -translate-x-1/2"
              style={{ left: `${bookmarkPercentage}%` }}
            >
              <div className="flex flex-col items-center gap-1">
                <Bookmark
                  className={`w-4 h-4 ${getBookmarkColor(bookmark.severity)} fill-current text-white`}
                />
                <span className="text-xs font-medium text-gray-600 whitespace-nowrap">
                  {bookmark.label}
                </span>
              </div>
            </div>
          );
        })}

        {/* Slider Track */}
        <div className="relative h-3 bg-gray-200 rounded-full overflow-hidden">
          {/* Past Track (Gray) */}
          <div
            className="absolute h-full bg-gray-400 transition-all duration-300"
            style={{ width: `${Math.min(percentage, nowPercentage)}%` }}
          />

          {/* Future Track (Gradient) */}
          <div
            className="absolute h-full bg-gradient-to-r from-blue-400 via-purple-400 to-purple-500 transition-all duration-300"
            style={{
              left: `${Math.max(percentage, nowPercentage)}%`,
              width: `${Math.max(0, percentage - nowPercentage)}%`
            }}
          />

          {/* NOW Marker */}
          <div
            className="absolute top-1/2 transform -translate-y-1/2 -translate-x-1/2 z-10"
            style={{ left: `${nowPercentage}%` }}
          >
            <div className="relative">
              <div className="w-6 h-6 bg-green-500 border-4 border-white rounded-full shadow-lg" />
              <div className="absolute -bottom-8 left-1/2 transform -translate-x-1/2 whitespace-nowrap">
                <span className="px-2 py-1 text-xs font-bold text-white bg-green-500 rounded shadow">
                  NOW
                </span>
              </div>
            </div>
          </div>

          {/* Slider Thumb */}
          <input
            type="range"
            min={range.min}
            max={range.max}
            step={step}
            value={timeOffset}
            onChange={handleSliderChange}
            onMouseEnter={() => setShowTooltip(true)}
            onMouseLeave={() => setShowTooltip(false)}
            className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-20"
            aria-label="Time offset slider"
          />

          {/* Custom Thumb */}
          <div
            className="absolute top-1/2 transform -translate-y-1/2 -translate-x-1/2 z-10 pointer-events-none transition-all duration-200"
            style={{ left: `${percentage}%` }}
          >
            <div className="w-8 h-8 bg-blue-500 border-4 border-white rounded-full shadow-xl">
              <div className="absolute inset-0 bg-blue-400 rounded-full animate-ping opacity-75" />
            </div>

            {/* Tooltip */}
            {showTooltip && (
              <div className="absolute -top-14 left-1/2 transform -translate-x-1/2 px-3 py-2 bg-gray-900 text-white text-sm font-medium rounded-lg shadow-xl whitespace-nowrap">
                {formatTimestamp(timeOffset)}
                <div className="absolute -bottom-1 left-1/2 transform -translate-x-1/2 w-2 h-2 bg-gray-900 rotate-45" />
              </div>
            )}
          </div>
        </div>

        {/* Time Labels */}
        <div className="flex justify-between mt-6 px-2">
          {[-180, -120, -60, 0, 60, 120, 180].map((offset) => (
            <div key={offset} className="flex flex-col items-center">
              <span className={`text-sm font-medium ${
                offset === 0 ? 'text-green-600' : 'text-gray-600'
              }`}>
                {formatTimeOffset(offset)}
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* Prediction Summary */}
      <div className="flex items-start gap-3 p-4 bg-blue-50 border-l-4 border-blue-500 rounded-lg">
        <Info className="w-5 h-5 text-blue-500 flex-shrink-0 mt-0.5" />
        <div className="flex-1">
          <h4 className="text-sm font-semibold text-gray-900 mb-1">
            Flood Impact at {formatTimeOffset(timeOffset)}
          </h4>
          <p className="text-sm text-gray-700">
            {timeOffset < 0 && 'Historical data from MindSpore GNN analysis.'}
            {timeOffset === 0 && 'Current real-time conditions from Sentinel-1 SAR.'}
            {timeOffset > 0 && `Predicted conditions based on ModelArts rainfall forecast and hydraulic simulation.`}
          </p>
        </div>
      </div>

      {/* Quick Jump Buttons */}
      <div className="flex gap-2">
        <button
          onClick={() => setTimeOffset(-180)}
          className="flex-1 px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors"
        >
          -3h (Start)
        </button>
        <button
          onClick={() => setTimeOffset(0)}
          className="flex-1 px-4 py-2 text-sm font-medium text-white bg-green-500 hover:bg-green-600 rounded-lg transition-colors"
        >
          NOW
        </button>
        <button
          onClick={() => setTimeOffset(180)}
          className="flex-1 px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors"
        >
          +3h (End)
        </button>
      </div>
    </div>
  );
};

export default TimeTravelSlider;
